name: Build and Unit Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        rust: ["stable"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: hecrj/setup-rust-action@v1.3.1
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt,clippy
      - name: Check Out Sources
        uses: actions/checkout@v1
      - name: Compile All Crates
        shell: bash
        run: cargo build --all
